export const RESPONSE_USER_SUCCESS = "RESPONSE_USER_SUCCESS";
export const RESPONSE_USER_FAIL = "RESPONSE_USER_FAIL";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAIL = "SESSION_FAIL";
export const RESPONSE_BOT_SUCCESS = "RESPONSE_BOT_SUCCESS";
export const RESPONSE_BOT_FAIL = "RESPONSE_BOT_FAIL";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";